
output: main.o application.o finance.o manager.o menu.o stock.o billing.o receptionist.o employee.o
	g++ main.o application.o finance.o manager.o menu.o stock.o billing.o receptionist.o employee.o -o output

main.o: main.cpp
	g++ -c main.cpp

application.o: application.cpp application.h
	g++ -c application.cpp

finance.o: finance.cpp finance.h
	g++ -c finance.cpp

manager.o: manager.cpp manager.h
	g++ -c manager.cpp

menu.o: menu.cpp menu.h
	g++ -c menu.cpp

stock.o: stock.cpp stock.h
	g++ -c stock.cpp

billing.o: billing.cpp billing.h
	g++ -c billing.cpp

receptionist.o: receptionist.cpp receptionist.h
	g++ -c receptionist.cpp

employee.o: employee.cpp employee.h
	g++ -c employee.cpp


